# 🐍 Numpy Kütüphanesi
---

## Neden Kullanıyoruz?
NumPy (Numerical Python), Python programlama dilinde bilimsel hesaplamalar, veri analizi ve makine öğrenimi için kullanılan en temel ve en popüler kütüphanedir. Python'un standart listeleri veri saklamak için esnek olsa da, matematiksel işlemler ve büyük veri setleri için yeterince hızlı ve verimli değildir.
```
pip install numpy
```
---

## Basit Kullanım (array, arrange, linspace)

In [1]:
import numpy as np
dizi_1 = np.array([0,1,2,3,4,5,6,7,8,9]) # Tek boyutlu dizi oluşturma
dizi_2 = np.arange(0,12,3) # 0 dan başla 12 ye kadar 3 er 3 er artarak gider
dizi_3 = np.linspace(0,5,5) # 0 ile 5 arasında 5 eşit parçaya böler

print(dizi_1)
print("*"*30)
print(dizi_2)
print("*"*30)
print(dizi_3)
print("*"*30)
print("dizi_1,",dizi_1.ndim,"boyutlu bir dizidir. Veri tipi:",dizi_1.dtype)

[0 1 2 3 4 5 6 7 8 9]
******************************
[0 3 6 9]
******************************
[0.   1.25 2.5  3.75 5.  ]
******************************
dizi_1, 1 boyutlu bir dizidir. Veri tipi: int64


---
## NumPy'da shape
Oluşturduğunuz bir dizinin (array) boyutlarını ve yapısını öğrenmenizi sağlayan bir özelliktir.

- 1 Boyutlu Dizi (Vektör): (eleman_sayısı,)
- 2 Boyutlu Dizi (Matris): (satır_sayısı, sütun_sayısı)
- 3 Boyutlu Dizi (Tensör): (derinlik, satır, sütun)

In [2]:
import numpy as np

dizi_1d = np.array([10, 20, 30, 40])

dizi_2d = np.array([
    [1, 2, 3], 
    [4, 5, 6]
])

dizi_3d = np.array([
    [
        [1, 2, 3, 4],
        [5, 6, 7, 8],
        [9, 10, 11, 12]
    ],
    [
        [13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]
    ]
])

print(dizi_1d.shape)
# Çıktı: (4,)
# Anlamı: Tek boyutta 4 eleman var. (Yanındaki virgül Python tuple yapısı gereğidir)

print(dizi_2d.shape)
# Çıktı: (2, 3)
# Anlamı: 2 Satır, 3 Sütun var.

print(dizi_3d.shape)
# Çıktı: (2, 3, 4)
# Anlamı: 2 katman (blok), her katmanda 3 satır, her satırda 4 sütun var.

(4,)
(2, 3)
(2, 3, 4)


---
## Matematiksel İşlemler


In [3]:
import numpy as np

# Örnek olarak iki dizi (array) oluşturalım
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([10, 20, 30, 40])

### Temel Aritmetik İşlemler
Bu işlemler eleman bazlıdır. Yani birinci dizinin 1. elemanı ile ikinci dizinin 1. elemanı işleme girer.
|İşlem|NumPy Fonksiyonu|Operatör|Açıklama|
|:-------------:|:-------------:|:-------------:|:-------------:|
|Toplama        |np.add()       |+              |Elemanları toplar| 
|Çıkarma        |np.subtract()  |-              |Elemanları çıkarır| 
|Çarpma         |np.multiply()  |*              |Elemanları çarpar| 
|Bölme          |np.divide()    |/              |Elemanları böler| 

In [4]:
# Toplama
toplam = np.add(arr1, arr2) 
# Alternatif: arr1 + arr2

# Çıkarma
fark = np.subtract(arr2, arr1)
# Alternatif: arr2 - arr1

# Çarpma
carpim = np.multiply(arr1, 5) # Tüm elemanları 5 ile çarpar (Broadcasting)

print(f"Toplam: {toplam}")
print(f"Fark: {fark}")
print(f"Çarpım (arr1 * 5): {carpim}")

# --- ÇIKTI ---
# Toplam: [11 22 33 44]
# Fark: [ 9 18 27 36]
# Çarpım (arr1 * 5): [ 5 10 15 20]

Toplam: [11 22 33 44]
Fark: [ 9 18 27 36]
Çarpım (arr1 * 5): [ 5 10 15 20]


### Üs Alma ve Karekök İşlemleri
Sayıların kuvvetini alma veya kökünü bulma işlemleri için kullanılır.
- **np.power(taban, üs)**: Üs alma işlemi ($x^y$).
- **np.sqrt(dizi):** Karekök alma işlemi ($\sqrt{x}$).
- **np.square(dizi):** Karesini alma işlemi ($x^2$).

In [5]:
# arr1 = [1, 2, 3, 4]

# Karesini alma
kareler = np.square(arr1)

# Karekök alma
karekok = np.sqrt(kareler)

# Üs alma (arr1 üzeri 3)
kup = np.power(arr1, 3)

print(f"Kareler: {kareler}")
print(f"Karekök: {karekok}")
print(f"Küp (x^3): {kup}")

# --- ÇIKTI ---
# Kareler: [ 1  4  9 16]
# Karekök: [1. 2. 3. 4.]
# Küp (x^3): [ 1  8 27 64]

Kareler: [ 1  4  9 16]
Karekök: [1. 2. 3. 4.]
Küp (x^3): [ 1  8 27 64]


### Trigonometrik İşlemler
NumPy, açıları varsayılan olarak radyan cinsinden kabul eder. Derece ile işlem yapmak isterseniz önce dönüştürmeniz gerekir.
- **np.sin()**, **np.cos()**, **np.tan()**: Sinüs, Kosinüs, Tanjant.
- **np.deg2rad()**: Dereceyi radyana çevirir.
- **np.rad2deg()**: Radyanı dereceye çevirir.

In [6]:
acilar_derece = np.array([0, 30, 45, 90])

# İşlem yapabilmek için dereceyi radyana çeviriyoruz
acilar_radyan = np.deg2rad(acilar_derece)

# Sinüs hesaplama
sinus_degerleri = np.sin(acilar_radyan)

print(f"Radyan: {acilar_radyan}")
print(f"Sinüs: {sinus_degerleri}")

# --- ÇIKTI ---
# Radyan: [0.         0.52359878 0.78539816 1.57079633]
# Sinüs: [0.         0.5        0.70710678 1.        ]

Radyan: [0.         0.52359878 0.78539816 1.57079633]
Sinüs: [0.         0.5        0.70710678 1.        ]


### Logaritmik ve Üstel İşlemler
Veri biliminde ve yapay sinir ağlarında aktivasyon fonksiyonlarında sıkça kullanılır.
- **np.exp()**: Euler sayısının kuvvetini alır ($e^x$).
- **np.log()**: Doğal logaritma ($ln$ veya $\log_e$).
- **np.log10()**: 10 tabanında logaritma.

In [7]:
data = np.array([1, 10, 100])

# e üzeri x hesaplama (e ≈ 2.718)
e_uzeri = np.exp(np.array([1])) # e^1

# 10 tabanında logaritma
log_10 = np.log10(data)

# Doğal logaritma (ln)
log_ln = np.log(data)

print(f"e^1 değeri: {e_uzeri}")
print(f"Log10: {log_10}")
print(f"Doğal Log (ln): {log_ln}")

# --- ÇIKTI ---
# e^1 değeri: [2.71828183]
# Log10: [0. 1. 2.]
# Doğal Log (ln): [0.         2.30258509 4.60517019]

e^1 değeri: [2.71828183]
Log10: [0. 1. 2.]
Doğal Log (ln): [0.         2.30258509 4.60517019]


### Yuvarlama ve Mutlak Değer İşlemleri
Ondalıklı sayıları tam sayıya çevirmek veya negatifleri pozitife çevirmek için kullanılır.
- **np.abs()**: Mutlak değer (negatifi pozitif yapar).
- **np.ceil()**: Yukarı yuvarlar (Tavan).
- **np.floor()**: Aşağı yuvarlar (Taban).
- **np.round()**: En yakın sayıya yuvarlar.

In [8]:
ondalikli = np.array([-3.7, -1.2, 2.5, 2.8])

mutlak = np.abs(ondalikli)  # |-3.7| = 3.7
yukari = np.ceil(ondalikli) # -3.7 -> -3, 2.8 -> 3
asagi = np.floor(ondalikli) # -3.7 -> -4, 2.8 -> 2
yakin = np.round(ondalikli) # Matematiksel yuvarlama

print(f"Orijinal: {ondalikli}")
print(f"Mutlak: {mutlak}")
print(f"Yukarı (Ceil): {yukari}")
print(f"Aşağı (Floor): {asagi}")
print(f"Yuvarla (Round): {yakin}")

Orijinal: [-3.7 -1.2  2.5  2.8]
Mutlak: [3.7 1.2 2.5 2.8]
Yukarı (Ceil): [-3. -1.  3.  3.]
Aşağı (Floor): [-4. -2.  2.  2.]
Yuvarla (Round): [-4. -1.  2.  3.]


### İstatistiksel ve Toplulaştırma (Aggregation) İşlemleri
Dizideki verileri özetlemek için kullanılır. Genelde tüm dizi üzerinden tek bir sonuç döner.
|Fonksiyon|Açıklama|
|:-------------:         |:-------------:|
|np.sum()                |Tüm elemanların toplamı|
|np.mean()               |Ortalama değer|
|np.median()             |Ortanca değer|
|np.std()                |Standart sapma (verinin ne kadar yayıldığı)|
|np.min() / np.max()     |En küçük ve en büyük değer|
|np.argmax()             |En büyük değerin indeksini verir|

In [9]:
veriler = np.array([10, 20, 50, 80, 100])

toplam_deger = np.sum(veriler)
ortalama = np.mean(veriler)
standart_sapma = np.std(veriler)
en_buyuk_index = np.argmax(veriler) # 100 değeri 4. indekste

print(f"Toplam: {toplam_deger}")
print(f"Ortalama: {ortalama}")
print(f"Standart Sapma: {standart_sapma}")
print(f"En büyük değerin indeksi: {en_buyuk_index}")

# --- ÇIKTI ---
# Toplam: 260
# Ortalama: 52.0
# Standart Sapma: 34.29...
# En büyük değerin indeksi: 4

Toplam: 260
Ortalama: 52.0
Standart Sapma: 34.292856398964496
En büyük değerin indeksi: 4


### Lineer Cebir (Matrix İşlemleri)
Özellikle yapay zeka modellerinde iki matrisin çarpımı (Dot Product) hayati önem taşır. Bu, eleman bazlı çarpma (*) işleminden farklıdır.
- **np.dot(a, b)**: Matris çarpımı (İç çarpım).

In [10]:
# 2x2'lik iki matris
matris_a = np.array([[1, 2], 
                     [3, 4]])

matris_b = np.array([[5, 6], 
                     [7, 8]])

# Matris Çarpımı (Dot Product)
# (1*5 + 2*7) , (1*6 + 2*8)
# (3*5 + 4*7) , (3*6 + 4*8)
sonuc = np.dot(matris_a, matris_b)

print("Matris Çarpımı Sonucu:\n", sonuc)

# --- ÇIKTI ---
# [[19 22]
#  [43 50]]

Matris Çarpımı Sonucu:
 [[19 22]
 [43 50]]


## Dizi Birleştirme ve Bölme
NumPy'da dizileri yönetirken boyut kavramı ($2 \times 3$, $3 \times 3$ matrisler gibi) çok önemlidir. İşlemleri genellikle "eksenler" (axis) üzerinden yaparız:
- Axis 0: Satırlar boyunca (Dikey/Aşağı doğru)
- Axis 1: Sütunlar boyunca (Yatay/Sana doğru)

|Komut|İşlem Yönü|Eşdeğeri|Görsel Analoji|
|:---:|:---|:---|:---|
|vstack|Dikey (Alt alta)|concatenate(axis=0)|Tuğla örmek (üst üste)|
|hstack|Yatay (Yan yana)|concatenate(axis=1)|Tren vagonlarını bağlamak|
|vsplit|Dikey Bölme|split(axis=0)|Pastayı yatay katmanlara ayırmak|
|hsplit|Yatay Bölme|split(axis=1)|Ekmeği dilimlemek|

### Dizi Birleştirme
Birden fazla diziyi tek bir dizi haline getirmek için kullanılır.

#### **np.concatenate**
En genel birleştirme fonksiyonudur. Dizileri belirtilen eksen (axis) boyunca birleştirir. Boyutların (birleştirilen eksen hariç) birebir uyuşması gerekir.

In [11]:
import numpy as np

# İki adet 2x2 matris oluşturalım
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

# --- AXIS 0 (Satır Bazlı/Alt Alta) Birleştirme ---
# Sanki yeni satırlar ekliyormuşuz gibi çalışır.
sonuc_dikey = np.concatenate((a, b), axis=0)

print("Axis 0 (Dikey) Birleştirme:\n", sonuc_dikey)
# Çıktı:
# [[1 2]
#  [3 4]
#  [5 6]
#  [7 8]]

# --- AXIS 1 (Sütun Bazlı/Yan Yana) Birleştirme ---
# Sanki yanına yeni sütunlar ekliyormuşuz gibi çalışır.
sonuc_yatay = np.concatenate((a, b), axis=1)

print("\nAxis 1 (Yatay) Birleştirme:\n", sonuc_yatay)
# Çıktı:
# [[1 2 5 6]
#  [3 4 7 8]]

Axis 0 (Dikey) Birleştirme:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]

Axis 1 (Yatay) Birleştirme:
 [[1 2 5 6]
 [3 4 7 8]]


#### **np.vstack** (Vertical Stack)
İsminden de anlaşılacağı gibi (Vertical) dikey yığma işlemi yapar. concatenate(axis=0) ile eşdeğerdir ancak sözdizimi daha basittir. Dizileri alt alta koyar. "**vstack**" kullanırken boyutların sütun sayılarının (yatay genişliğin) eşit olması gerekir.

In [12]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# İki adet 1 boyutlu diziyi alt alta koyarak 2x3 bir matris elde ederiz
sonuc = np.vstack((a, b))

print("Vstack Sonucu:\n", sonuc)
# Çıktı:
# [[1 2 3]
#  [4 5 6]]

Vstack Sonucu:
 [[1 2 3]
 [4 5 6]]


#### **np.hstack** (Horizontal Stack)
(Horizontal) yatay yığma işlemi yapar. concatenate(axis=1) ile eşdeğerdir. Dizileri yan yana (tren vagonu ekler gibi) birleştirir. "**hstack**" kullanırken dizilerin satır sayılarının (dikey yüksekliğin) eşit olması gerekir.

In [13]:
import numpy as np

a = np.array([[1], [2], [3]])  # 3x1 dikey vektör
b = np.array([[4], [5], [6]])  # 3x1 dikey vektör

# Yan yana koyarak 3x2 bir matris elde ederiz
sonuc = np.hstack((a, b))

print("Hstack Sonucu:\n", sonuc)
# Çıktı:
# [[1 4]
#  [2 5]
#  [3 6]]

Hstack Sonucu:
 [[1 4]
 [2 5]
 [3 6]]


### Dizi Bölme
Birleşmiş bir diziyi daha küçük alt dizilere ayırmak için kullanılır.

#### **np.split**
En genel bölme fonksiyonudur. Diziyi eşit parçalara bölebilir veya belirttiğiniz indeks noktalarından kesebilir.

In [14]:
import numpy as np

x = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8])

# 1. Yöntem: Eşit parçalara bölme (Burada 3 eşit parçaya bölüyoruz)
parcalar = np.split(x, 3)
print("Eşit Bölme:", parcalar)
# Çıktı: [array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]

# 2. Yöntem: Belirli indekslerden kesme
# 3. ve 6. indekslerden bıçakla kesiyormuş gibi düşünün
kisiye_ozel = np.split(x, [3, 6])
print("İndeksli Bölme:", kisiye_ozel)
# Çıktı:
# [0, 1, 2] -> Başlangıçtan 3'e kadar
# [3, 4, 5] -> 3'ten 6'ya kadar
# [6, 7, 8] -> 6'dan sona kadar

Eşit Bölme: [array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]
İndeksli Bölme: [array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]


#### **np.vsplit** (Vertical Split)
Dikey olarak (satırlar boyunca) bölme işlemi yapar. Yatay bir "bıçak" ile diziyi kestiğinizi hayal edin. Sadece 2 veya daha fazla boyutu olan dizilerde çalışır.

In [15]:
import numpy as np

# 4x4'lük bir matris oluşturalım (0'dan 15'e kadar)
matris = np.arange(16).reshape(4, 4)

# Matrisi tam ortadan ikiye, dikey eksende bölüyoruz
ust_kisim, alt_kisim = np.vsplit(matris, 2)

print("Orijinal:\n", matris)
print("\nÜst Kısım:\n", ust_kisim)
print("\nAlt Kısım:\n", alt_kisim)

Orijinal:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

Üst Kısım:
 [[0 1 2 3]
 [4 5 6 7]]

Alt Kısım:
 [[ 8  9 10 11]
 [12 13 14 15]]


#### **np.hsplit** (Horizontal Split)
Yatay olarak (sütunlar boyunca) bölme işlemi yapar. Dikey bir "bıçak" ile diziyi yukarıdan aşağıya kestiğinizi hayal edin.

In [16]:
import numpy as np

# 2x4'lük bir matris
matris = np.array([[10, 20, 30, 40],
                   [50, 60, 70, 80]])

# Sütunları 2 eşit parçaya böl (Her parçada 2 sütun olacak)
sol_taraf, sag_taraf = np.hsplit(matris, 2)

print("Sol Taraf:\n", sol_taraf)
# Çıktı:
# [[10 20]
#  [50 60]]

print("Sağ Taraf:\n", sag_taraf)
# Çıktı:
# [[30 40]
#  [70 80]]

Sol Taraf:
 [[10 20]
 [50 60]]
Sağ Taraf:
 [[30 40]
 [70 80]]
